# recipe/meta.yaml
{% set name = "pmultiqc" %}
{% set version = "0.0.32" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python >=3.10
    - pip
    - poetry-core
  run:
    - python >=3.10
    - pytest
    - lxml
    - multiqc >=1.29
    - pandas
    - sdrf-pipelines >=0.0.32
    - pyteomics
    - pyopenms
    - numpy >=1.23
    - pyarrow
    - scikit-learn >=1.2
    - lxml

test:
  imports:
    - pmultiqc
    - pmultiqc.modules
    - pmultiqc.modules.quantms

about:
  home: "https://github.com/bigbio/pmultiqc/"
  license: MIT
  license_family: MIT
  summary: "Python package for quality control of proteomics datasets, based on multiqc package"
  doc_url: https://github.com/bigbio/pmultiqc/
  dev_url: https://github.com/bigbio/pmultiqc/

extra:
  recipe-maintainers:
    - ypriverol