name: Service Issue
description: Report issues with the PRIDE PMultiQC web service
title: "[SERVICE] "
labels: ["service", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue with the PRIDE PMultiQC service! Please provide details about the problem you encountered.

  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: A clear and concise description of the issue you encountered.
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. Go to 'https://www.ebi.ac.uk/pride/services/pmultiqc/'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: Error Message
      description: If you received an error message, please paste it here.
      placeholder: Paste the error message here...
      render: shell

  - type: input
    id: job_id
    attributes:
      label: Job ID (if applicable)
      description: If you have a job ID, please provide it here.
      placeholder: e.g., abc123-def456-ghi789

  - type: input
    id: pride_accession
    attributes:
      label: PRIDE Accession (if applicable)
      description: If you were analyzing a PRIDE dataset, provide the accession number.
      placeholder: e.g., PXD003133

  - type: textarea
    id: browser_info
    attributes:
      label: Browser Information
      description: Information about your browser and system
      placeholder: |
        - Browser: [e.g., Chrome 120.0, Firefox 121.0, Safari 17.0]
        - OS: [e.g., Windows 10, macOS 13.0, Ubuntu 20.04]
        - Any browser extensions that might interfere?

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context, information, or details about the issue.
      placeholder: Add any other relevant information...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true