apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: GitHub Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      credentials: secret:argocd-image-updater/ghcr-creds
  git.user: argocd-image-updater
  git.email: noreply@argocd.example.com
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-creds
  namespace: argocd
type: Opaque
stringData:
  username: $GITHUB_USERNAME
  password: $GITHUB_TOKEN
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pmultiqc-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: pmultiqc=ghcr.io/bigbio/pmultiqc
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/bigbio/pmultiqc
    targetRevision: HEAD
    path: pmultiqc_service/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: pmultiqc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
