apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pmultiqc-uploads-pvc
  namespace: pmultiqc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pmultiqc-outputs-pvc
  namespace: pmultiqc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath 