version: '3.8'
services:
  pmultiqc-service:
    build:
      context: ../
      dockerfile: Dockerfile
    image: pmultiqc-service:dev
    container_name: pmultiqc-service-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MAX_CONTENT_LENGTH=1073741824  # 1GB upload limit for dev
      - UPLOAD_FOLDER=/app/uploads
      - OUTPUT_FOLDER=/app/outputs
      - HTML_REPORTS_FOLDER=/app/reports
      - BASE_URL=http://localhost:5000
      - LOG_LEVEL=DEBUG
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./reports:/app/reports
      - ./config.yaml:/app/config.yaml:ro
      - ../:/app:ro  # Mount source code for development
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4Gi  # Reduced for development
          cpus: '2.0'
        reservations:
          memory: 2Gi
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
